---
title: "Syllabus"
author: "Author: Matthew J. Cossley"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float:
        collapsed: true
        smooth_scroll: true
    toc_depth: 3
    fig_caption: yes
    number_sections: false
    theme: cosmo
fontsize: 14pt
---

## Course Websites
Please reference the following course websites for course
details:

- [Course Materials](https://crossley.github.io/cogs3020/)
- [iLearn](https://ilearn.mq.edu.au/course/view.php?id=38800)
- [Unit Guide](https://unitguides.mq.edu.au/unit_offerings/123650/unit_guide)

## Instructor Information
- **Name:** Dr. Matthew J. Crossley
- **Email:** matthew.crossley@mq.edu.au
- **Office:** Australian Hearing Hub 3.819
- **Office Hours:** By appointment

<!-- ## Tutor Information -->
<!-- - **Name:** TBA -->
<!-- - **Email:** TBS -->
<!-- - **Office:** TBA -->
<!-- - **Office Hours:** TBA -->

## Course Schedule
|          | Day       | Time                | Location                            |
|----------|-----------|---------------------|-------------------------------------|
| Lecture  | Friday    | 10:00 AM - 11:00 AM | Online                              |
| Tutorial | Thursday  | 9:00 AM - 10:00 AM  | 12 Second Way - 318 Faculty PC Room |

- [Lecture and tutorial Zoom link](https://macquarie.zoom.us/my/matthewcrossley)

## Weekly Lectures

- Please see [lectures](lectures.html)

- Course content will be delivered with agility. We will
slow down or speed up as need and want demands.

## Course Philosophy
**Python competency**: We will spend a little time working
together to learn `Python` but I will be moving faster than
I do in my second year statistics unit where many of you
might have learned `R`. This course assumes you have a solid
enough programming background to pick up Python as we go.

**Computational literacy**: The main objective of the course
is for you to be able to spend time with published
computational modelling papers, and replicate most or all of
the results in those papers. This is a super power among
cognitive neuroscientist.

**Mathematical literacy**: Math is beautiful and useful and
I encourage to learn as much of it as you can. A good goal
for a casual computational modeller is to have made it
through linear algebra, calculus, and a first year
differential equations unit. However, you can still do well,
have a great time, and learn a lot in this unit without that
much of a math background. You will certainly have to
tolerate looking at some fancy looking math --- e.g.,
derivatives ($\frac{d}{dx}f(x)$), integrals ($\int x dx$),
and differential equations  ($\frac{d}{dx}f(x) = g(x)$) ---
but the emphasis will be on translating these things into
code, not on interacting with them much in the abstract.

## Performance Evaluation
- 10% quizzes
- 30% problem sets
- 30% midterm exam
- 30% final exam

**Quizzes**: 10 short online multiple quizzes designed to
provide routine assessment and feedback. Graded on
credit/no-credit basis. The 2 lowest quizzes (missed or
marked non-credit) may be dropped without penalty. These
will not be hard. They are simple nudges to motivate you to
study lecture notes **before** lecture begins.

**Problem sets**: These are where most of your learning will
occur. They will require hard work and it is essential that
you take them seriously and commit adequate time to them.
They will closely follow the lecture notes.

**Midterm exam**: This will take the form of a 1 page
proposal in which you choose a computational model from the
literature and choose key results from this paper that you
will replicate for the final exam.

**Final exam**: This will take the form of a final report
and / or presentation to the class (class size and time
allowing) about a computational model from the literature
that you selected as part of your midterm exam. You will be
responsible for replicating key findings from this paper
with code that you have written from scratch.

## Readings

The essentials will all be included in the lecture notes,
but more complete information and structure from each
lecture can be found in references listed below. For now,
there are only two books that I know I will draw from, and
the rest will be journal articles. I will make announcements
and keep you all informed if this list changes.

* Izhikevich, E. M. (2006). Dynamical Systems in
Neuroscience: The Geometry of Excitability and Bursting. The
MIT Press.

  * https://www.izhikevich.org/publications/dsn.pdf

* Sutton, R. S., & Barto, A. G. (1998). Reinforcement
learning: An introduction. MIT Press.

  * https://web.stanford.edu/class/psych209/Readings/SuttonBartoIPRLBook2ndEd.pdf


## Project ideas

Please see below for a list of some modelling papers that I
think would be appropriate for you to base your final
projects in. Use Google Scholar to look these up and grab
the pdfs. If you have trouble, email me directly and I will
help you out.

* Ashby, F. G., & Crossley, M. J. (2011). A Computational
Model of How Cholinergic Interneurons Protect
Striatal-dependent Learning. Journal of Cognitive
Neuroscience, 23(6), 1549–1566.

* Daw, N. D., Niv, Y., & Dayan, P. (2005). Uncertainty-based
competition between prefrontal and dorsolateral striatal
systems for behavioral control. Nature Neuroscience, 8(12),
1704–1711.

* Frank, M. J. (2004). By Carrot or by Stick: Cognitive
Reinforcement Learning in Parkinsonism. Science, 306(5703),
1940–1943.

* Gurney, K. N., Humphries, M. D., & Redgrave, P. (2015). A
New Framework for Cortico-Striatal Plasticity: Behavioural
Theory Meets In Vitro Data at the Reinforcement-Action
Interface. PLoS Biology, 13(1), e1002034.

* Kubilius, J., Schrimpf, M., Nayebi, A., Bear, D., Yamins,
D. L. K., & DiCarlo, J. J. (2018). CORnet: Modeling the
Neural Mechanisms of Core Object Recognition [Preprint].
Neuroscience.

* Moustafa, A. A., Gilbertson, M. W., Orr, S. P.,
Herzallah, M. M., Servatius, R. J., & Myers, C. E. (2013). A
model of amygdala–hippocampal–prefrontal interaction in fear
conditioning and extinction in animals. Brain and Cognition,
81(1), 29–43.

* Ponzi, A., & Wickens, J. (2010). Sequentially Switching
Cell Assemblies in Random Inhibitory Networks of Spiking
Neurons in the Striatum. Journal of Neuroscience, 30(17),
5894–5911.

* Smith, M. A., Ghazizadeh, A., & Shadmehr, R. (2006).
Interacting Adaptive Processes with Different Timescales
Underlie Short-Term Motor Learning. PLoS Biology, 4(6).

